ci: fix the 32 byte inaccuracy of SDK size reports
Part of: https://linear.app/customerio/issue/MBL-155/track-the-binary-size-of-our-ios-sdk-upon-every-release

As called out in the ticket, the SDK size report comparing main branch to open PRs is inaccurate by 32 bytes. This commit fixes this so if you open a PR and not modify any code in it, the diff should show 0 bytes difference.

Testing consideration:
* The PR should see SDK size reports generated as before. QA sample app builds created and uploaded as before.
* We cannot fully test this until we merge into main and the main branch creates a new cache.

Notes for reviewer:
* I fixed this issue by setting up the CI to compile a version of the APN sample app that does not modify the Version.swift file. This compiled app is used to generate SDK size report. The CI continues to compile sample apps for QA testing and it should work as previously expected.
* Because the generate-sdk-size-report action is now compiling sample apps, I created a new action, build-sample-app, to make building a sample app re-usable.
* "fastlane ios build" command now takes optional arguments to configure it. QA sample apps will make builds differently then builds for generating SDK size reports.

commit-id:eddb8612

diff --git a/.github/actions/generate-sdk-size-report/action.yml b/.github/actions/generate-sdk-size-report/action.yml
--- a/.github/actions/generate-sdk-size-report/action.yml
+++ b/.github/actions/generate-sdk-size-report/action.yml
@@ -1,16 +1,12 @@
 name: Generate SDK size reports 
 # We only need to use 1 sample app build to generate the SDK size diff report. Therefore, we are hard-coding APN-UIKit into this action.
-description: Given a .xcarchive for the APN sample app, this action will generate all of the SDK size reports. 
+description: Run this action to generate all of the SDK size reports. 
 
-inputs:  
-  apn-app-xcarchive-name:
-    description: 'The name of the .xcarchive located inside of Apps/APN-UIKit/build/ to generate reports for. Example: "App.xcarchive"'
+inputs:
+  GOOGLE_CLOUD_MATCH_READONLY_SERVICE_ACCOUNT_B64:
+    description: 'Maps to the secret, GOOGLE_CLOUD_MATCH_READONLY_SERVICE_ACCOUNT_B64. Used for code signing. See the Fastlane config files to learn more.'
     type: string
-    required: true    
-  generate-main-diff-report:
-    description: 'Whether to generate the SDK size diff report between the main branch and the PR branch. If you are running on a PR, set this to true'
-    type: boolean
-    required: true 
+    required: true
 
 # 3 separate SDK size reports may be generated by this action. 
 outputs:
@@ -21,24 +17,39 @@ outputs:
     description: 'The SDK size report, as a string. This report includes dependencies as well as the SDK size.'
     value: ${{ steps.sdk-size-including-dependencies-report.outputs.stdout }}
   sdk-size-diff-report:
-    description: 'The SDK size report, as a string. This report is the size difference between passed in app and the last build on main branch. Only populated if generate-main-diff-report input variable is true.'
+    description: 'The SDK size report, as a string. This report is the size difference between the current branch code and the last build on main branch. Only populated if this action is run from a pull request.'
     value: ${{ steps.sdk-size-diff-report.outputs.stdout }}
 
 runs:
   using: "composite"
   steps:
-  - name: Set environment variables for convenience in future steps 
-    shell: bash
-    # Use each of the set variables in future steps like: ${{ env.WORKING_DIRECTORY }}    
-    run: echo "WORKING_DIRECTORY=Apps/APN-UIKit/build" >> $GITHUB_ENV
-
   - name: Assert running on macOS runner. Bloaty requires some complex compilation to run on Linux. Therefore, this action only supports macOS runners.
     shell: bash
     run: test $RUNNER_OS = 'macOS'
 
   - name: Install bloaty, in case it is not already 
     shell: bash
-    run: brew install bloaty || true # If it's already installed, this will fail without error
+    run: brew install bloaty || true # If it's already installed, this will fail without error    
+
+  - name: Make a build of the sample app to generate report for 
+    uses: ./.github/actions/build-sample-app
+    id: build-sample-app
+    with:
+      apn-or-fcm: 'APN'
+      sample-app: 'APN-UIKit'
+      # Pass in a hard-coded version and build number to ensure that all sample app builds that are compiled for SDK size reports are consistent.
+      # When we compare size reports between different builds, we want to ensure that the only difference is the SDK code that was modified in a PR. 
+      fastlane-build-args: '{"app_version": "1.0.0", "build_number": "1"}'
+      # workspace credentials do not matter since we are not using this app build. 
+      customerio-workspace-siteid: "12345"
+      customerio-workspace-cdp-api-key: "12345"      
+      GOOGLE_CLOUD_MATCH_READONLY_SERVICE_ACCOUNT_B64: ${{ inputs.GOOGLE_CLOUD_MATCH_READONLY_SERVICE_ACCOUNT_B64 }}
+
+  - name: Save the sample app build, if this is a main branch build 
+    if: github.ref == 'refs/heads/main'   
+    uses: ./.github/actions/main-sample-app-build 
+    with:
+      apn-app-xcarchive-name: ${{ steps.build-sample-app.outputs.app-xcarchive-name }}
 
   - name: Make the SDK size report
     uses: mathiasvr/command-output@v2.0.0
@@ -46,8 +57,8 @@ runs:
     with:
       run: |
         bloaty --source-filter ".*(customerio-ios\/Sources).*" \
-          -d compileunits --debug-file=${{ env.WORKING_DIRECTORY }}/${{ inputs.apn-app-xcarchive-name }}/dSYMs/APN\ UIKit.app.dSYM/Contents/Resources/DWARF/APN\ UIKit \
-          ${{ env.WORKING_DIRECTORY }}/${{ inputs.apn-app-xcarchive-name }}/Products/Applications/APN\ UIKit.app/APN\ UIKit \
+          -d compileunits --debug-file=${{ steps.build-sample-app.outputs.app-xcarchive-path }}/dSYMs/APN\ UIKit.app.dSYM/Contents/Resources/DWARF/APN\ UIKit \
+          ${{ steps.build-sample-app.outputs.app-xcarchive-path }}/Products/Applications/APN\ UIKit.app/APN\ UIKit \
           -n 0 
     
   - name: Make the SDK size report, including dependencies
@@ -56,15 +67,15 @@ runs:
     with: 
       run: |
         bloaty --source-filter ".*(customerio-ios\/Sources)|(SourcePackages\/checkouts).*" \
-          -d compileunits --debug-file=${{ env.WORKING_DIRECTORY }}/${{ inputs.apn-app-xcarchive-name }}/dSYMs/APN\ UIKit.app.dSYM/Contents/Resources/DWARF/APN\ UIKit \
-          ${{ env.WORKING_DIRECTORY }}/${{ inputs.apn-app-xcarchive-name }}/Products/Applications/APN\ UIKit.app/APN\ UIKit \
+          -d compileunits --debug-file=${{ steps.build-sample-app.outputs.app-xcarchive-path }}/dSYMs/APN\ UIKit.app.dSYM/Contents/Resources/DWARF/APN\ UIKit \
+          ${{ steps.build-sample-app.outputs.app-xcarchive-path }}/Products/Applications/APN\ UIKit.app/APN\ UIKit \
           -n 0 
   
   # We want to determine if the SDK's binary size will change after merging a PR. 
   # To do that, we take the latest sample app build from the main branch and compare it to the app passed into this action. 
 
   - name: Download latest main sample app build to generate SDK size diff report       
-    if: ${{ inputs.generate-main-diff-report }} == true
+    if: ${{ github.event_name == 'pull_request' }}
     id: download-latest-main-build
     uses: ./.github/actions/main-sample-app-build
 
@@ -76,5 +87,5 @@ runs:
       run: |
         bloaty --source-filter ".*(customerio-ios\/Sources).*" -d compileunits \
           --debug-file="${{ steps.download-latest-main-build.outputs.apn-app-xcarchive-path }}/dSYMs/APN UIKit.app.dSYM/Contents/Resources/DWARF/APN UIKit" \
-          --debug-file="${{ env.WORKING_DIRECTORY }}/${{ inputs.apn-app-xcarchive-name }}/dSYMs/APN UIKit.app.dSYM/Contents/Resources/DWARF/APN UIKit" \
-          "${{ env.WORKING_DIRECTORY }}/${{ inputs.apn-app-xcarchive-name }}/Products/Applications/APN UIKit.app/APN UIKit" -- "${{ steps.download-latest-main-build.outputs.apn-app-xcarchive-path }}/Products/Applications/APN UIKit.app/APN UIKit" 
+          --debug-file="${{ steps.build-sample-app.outputs.app-xcarchive-path }}/dSYMs/APN UIKit.app.dSYM/Contents/Resources/DWARF/APN UIKit" \
+          "${{ steps.build-sample-app.outputs.app-xcarchive-path }}/Products/Applications/APN UIKit.app/APN UIKit" -- "${{ steps.download-latest-main-build.outputs.apn-app-xcarchive-path }}/Products/Applications/APN UIKit.app/APN UIKit" 
