Revert "Giving up on using DWARF 4. Trying a HEAD build of bloaty to get DWARF 5 support."
This reverts commit a1a92c8c905599d2854f950c8c6cfea82576f188.

diff --git a/.github/actions/generate-sdk-size-report/action.yml b/.github/actions/generate-sdk-size-report/action.yml
--- a/.github/actions/generate-sdk-size-report/action.yml
+++ b/.github/actions/generate-sdk-size-report/action.yml
@@ -44,16 +44,9 @@ runs:
       xcodebuild -downloadPlatform iOS 
     shell: bash
 
-  - name: Install bloaty from source with DWARF 5 support
+  - name: Install bloaty, in case it is not already 
     shell: bash
-    run: |
-      # Check if bloaty is already installed and up to date
-      if command -v bloaty &> /dev/null; then
-        echo "bloaty is already installed"
-      else
-        # Install bloaty from HEAD to get latest DWARF 5 support
-        brew install --HEAD bloaty
-      fi    
+    run: brew install bloaty || true # If it's already installed, this will fail without error    
 
   - name: Make a build of the sample app to generate report for 
     uses: ./.github/actions/build-sample-app
